In [1]:
import pandas as pd
import numpy as np
import ast

#To Ignore Warnings in Output
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Load in the data
business = pd.read_csv('../data/output_csv/business_PA_Philly_clean.csv')
review = pd.read_csv('../data/output_csv/review_PA_Philly_clean.csv')

In [3]:
business.head()

,business_id,name,address,city,postal_code,latitude,longitude,stars,review_count,categories,...,Seafood Markets,Wraps,Shaved Ice,Cupcakes,Greek,Flowers & Gifts,Home & Garden,French,Candy Stores,Chocolatiers & Shops
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,19107,39.955505,-75.155564,4.0,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,205 Race St,Philadelphia,19106,39.953949,-75.143226,4.0,245,"Sushi Bars, Restaurants, Japanese",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ROeacJQwBeh05Rqg7F6TCg,BAP,1224 South St,Philadelphia,19147,39.943223,-75.162568,4.5,205,"Korean, Restaurants",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,aPNXGTDkf-4bjhyMBQxqpQ,Craft Hall,901 N Delaware Ave,Philadelphia,19123,39.962582,-75.135657,3.5,65,"Eatertainment, Arts & Entertainment, Brewpubs,...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ppFCk9aQkM338Rgwpl2F5A,Wawa,3604 Chestnut St,Philadelphia,19104,39.954573,-75.194894,3.0,56,"Restaurants, Automotive, Delis, Gas Stations, ...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
review.head()

,review_id,user_id,business_id,stars,year
0,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,2015
1,oyaMhzBSwfGgemSGuZCdwQ,Dd1jQj7S-BFGqRbApFzCFw,YtSqYv1Q_pOltsVPSx54SA,5,2013
2,Xs8Z8lmKkosqW5mw_sVAoA,IQsF3Rc6IgCzjVV9DE8KXg,eFvzHawVJofxSnD7TgbZtg,5,2014
3,JBWZmBy69VMggxj3eYn17Q,aFa96pz67TwOFu4Weq5Agg,kq5Ghhh14r-eCxlVmlyd8w,5,2018
4,YcLXh-3UC9y6YFAI9xxzPQ,G0DHgkSsDozqUPWtlxVEMw,oBhJuukGRqPVvYBfTkhuZA,4,2015

In [5]:
business = business.drop(columns = ['BYOBCorkage','NoiseLevel','RestaurantsAttire','RestaurantsPriceRange2','WiFi','AgesAllowed'])

In [6]:
X = business.columns[11:]

In [7]:
for i in range(len(X)):
    column_name = X[i]
    print(column_name)
    print("---------------")
    business[column_name] = business[column_name].astype(int)
    print(business[column_name].unique())
    print("***************")

AcceptsInsurance
---------------
[0 1]
***************
Alcohol
---------------
[0 1]
***************
Ambience
---------------
[0 1]
***************
BYOB
---------------
[0 1]
***************
BestNights
---------------
[0 1]
***************
BikeParking
---------------
[1 0]
***************
BusinessAcceptsBitcoin
---------------
[0 1]
***************
BusinessAcceptsCreditCards
---------------
[0 1]
***************
BusinessParking
---------------
[1 0]
***************
ByAppointmentOnly
---------------
[0 1]
***************
Caters
---------------
[1 0]
***************
CoatCheck
---------------
[0 1]
***************
Corkage
---------------
[0 1]
***************
DietaryRestrictions
---------------
[0 1]
***************
DogsAllowed
---------------
[0 1]
***************
DriveThr
---------------
[0 1]
***************
GoodForDancing
---------------
[0 1]
***************
GoodForKids
---------------
[0 1]
***************
GoodForMeal
---------------
[0 1]
***************
HappyHour
---------------
[0 1]
***************
HasTV
---------------
[0 1]
***************
Music
---------------
[0 1]
***************
Open24Hours
---------------
[0 1]
***************
OutdoorSeating
---------------
[0 1]
***************
RestaurantsCounterService
---------------
[0 1]
***************
RestaurantsDelivery
---------------
[0 1]
***************
RestaurantsGoodForGroups
---------------
[0 1]
***************
RestaurantsReservations
---------------
[0 1]
***************
RestaurantsTableService
---------------
[0 1]
***************
RestaurantsTakeOut
---------------
[1 0]
***************
Smoking
---------------
[0 1]
***************
WheelchairAccessible
---------------
[0 1]
***************
Pizza
---------------
[0 1]
***************
Sandwiches
---------------
[0 1]
***************
Nightlife
---------------
[0 1]
***************
Bars
---------------
[0 1]
***************
Coffee & Tea
---------------
[1 0]
***************
American (Traditional)
---------------
[0 1]
***************
Breakfast & Brunch
---------------
[0 1]
***************
Italian
---------------
[0 1]
***************
American (New)
---------------
[0 1]
***************
Specialty Food
---------------
[0 1]
***************
Burgers
---------------
[0 1]
***************
Fast Food
---------------
[0 1]
***************
Event Planning & Services
---------------
[0 1]
***************
Shopping
---------------
[0 1]
***************
Chinese
---------------
[0 1]
***************
Grocery
---------------
[0 1]
***************
Bakeries
---------------
[1 0]
***************
Seafood
---------------
[0 1]
***************
Delis
---------------
[0 1]
***************
Mexican
---------------
[0 1]
***************
Salad
---------------
[0 1]
***************
Desserts
---------------
[0 1]
***************
Convenience Stores
---------------
[0 1]
***************
Caterers
---------------
[0 1]
***************
Beer
---------------
[0 1]
***************
Wine & Spirits
---------------
[0 1]
***************
Cafes
---------------
[0 1]
***************
Ice Cream & Frozen Yogurt
---------------
[0 1]
***************
Chicken Wings
---------------
[0 1]
***************
Japanese
---------------
[0 1]
***************
Drugstores
---------------
[0 1]
***************
Donuts
---------------
[0 1]
***************
Asian Fusion
---------------
[0 1]
***************
Juice Bars & Smoothies
---------------
[0 1]
***************
Pubs
---------------
[0 1]
***************
Sushi Bars
---------------
[0 1]
***************
Cheesesteaks
---------------
[0 1]
***************
Sports Bars
---------------
[0 1]
***************
Cocktail Bars
---------------
[0 1]
***************
Vegetarian
---------------
[0 1]
***************
Venues & Event Spaces
---------------
[0 1]
***************
Arts & Entertainment
---------------
[0 1]
***************
Steakhouses
---------------
[0 1]
***************
Mediterranean
---------------
[0 1]
***************
Diners
---------------
[0 1]
***************
Soup
---------------
[0 1]
***************
Food Delivery Services
---------------
[0 1]
***************
Barbeque
---------------
[0 1]
***************
Bagels
---------------
[0 1]
***************
Food Trucks
---------------
[0 1]
***************
Health & Medical
---------------
[0 1]
***************
Thai
---------------
[0 1]
***************
Breweries
---------------
[0 1]
***************
Vegan
---------------
[0 1]
***************
Indian
---------------
[0 1]
***************
Beer Bar
---------------
[0 1]
***************
Chicken Shop
---------------
[0 1]
***************
Fruits & Veggies
---------------
[0 1]
***************
Farmers Market
---------------
[0 1]
***************
Pharmacy
---------------
[0 1]
***************
Gastropubs
---------------
[0 1]
***************
Wine Bars
---------------
[0 1]
***************
Meat Shops
---------------
[0 1]
***************
Hot Dogs
---------------
[0 1]
***************
Caribbean
---------------
[0 1]
***************
Comfort Food
---------------
[0 1]
***************
Gluten-Free
---------------
[0 1]
***************
Vietnamese
---------------
[0 1]
***************
Automotive
---------------
[0 1]
***************
Local Flavor
---------------
[0 1]
***************
Lounges
---------------
[0 1]
***************
Bubble Tea
---------------
[1 0]
***************
Korean
---------------
[0 1]
***************
Ethnic Food
---------------
[0 1]
***************
Middle Eastern
---------------
[0 1]
***************
Halal
---------------
[0 1]
***************
Gas Stations
---------------
[0 1]
***************
Fashion
---------------
[0 1]
***************
Tacos
---------------
[0 1]
***************
Noodles
---------------
[0 1]
***************
Hotels & Travel
---------------
[0 1]
***************
Soul Food
---------------
[0 1]
***************
Tex-Mex
---------------
[0 1]
***************
Latin American
---------------
[0 1]
***************
Department Stores
---------------
[0 1]
***************
Health Markets
---------------
[0 1]
***************
Food Stands
---------------
[0 1]
***************
Active Life
---------------
[0 1]
***************
Seafood Markets
---------------
[0 1]
***************
Wraps
---------------
[0 1]
***************
Shaved Ice
---------------
[0 1]
***************
Cupcakes
---------------
[0 1]
***************
Greek
---------------
[0 1]
***************
Flowers & Gifts
---------------
[0 1]
***************
Home & Garden
---------------
[0 1]
***************
French
---------------
[0 1]
***************
Candy Stores
---------------
[0 1]
***************
Chocolatiers & Shops
---------------
[0 1]
***************

In [8]:
business_categories = business.iloc[:,11:]

In [9]:
business_categories['business_id'] = business['business_id']

In [10]:
business_categories.index = business_categories['business_id']

In [11]:
business_categories = business_categories.drop(columns = ['business_id'])

In [12]:
business_categories

,AcceptsInsurance,Alcohol,Ambience,BYOB,BestNights,BikeParking,BusinessAcceptsBitcoin,BusinessAcceptsCreditCards,BusinessParking,ByAppointmentOnly,...,Seafood Markets,Wraps,Shaved Ice,Cupcakes,Greek,Flowers & Gifts,Home & Garden,French,Candy Stores,Chocolatiers & Shops
business_id,,,,,,,,,,,,,,,,,,,,,
MTSW4McQd7CbVtyjqoe9mw,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
MUTTqe8uqyMdBl186RmNeA,0,1,1,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
ROeacJQwBeh05Rqg7F6TCg,0,0,1,0,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
aPNXGTDkf-4bjhyMBQxqpQ,0,0,1,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
ppFCk9aQkM338Rgwpl2F5A,0,0,1,0,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
K1SsvIPfFcHniNSPc3IG7g,0,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
mzTTdvQGkUHZ8ii7OnZC5w,0,0,0,0,0,1,0,1,1,0,...,0,0,0,0,0,1,0,0,0,0
OfRbGvHn-nAnQMqNxiIpcA,0,1,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
wVxXRFf10zTTAs11nr4xeA,0,0,1,0,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
WnT9NIzQgLlILjPT0kEcsQ,0,0,1,0,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0

# Content Based

Approach 1

In [13]:
# First let's calculate the cosine similarity of the restaurants (based on categories)
from sklearn.metrics.pairwise import cosine_similarity

business_categories_sim = cosine_similarity(business_categories)

business_categories_sim = pd.DataFrame(business_categories_sim, index = business_categories.index, columns = business_categories.index)

In [14]:
business_names = business.loc[:,['business_id', 'name']]

In [15]:
# The following function will take in the business id, then returns the top n recommendations.
def print_recommendations(original_item, top_n):
    """
    inputs: original_item <int>: is the id of the item we want to make 
                                 recommendation for
            top_n <int>: number of items we want to recommend for the 
                         original item
    """
    idx = original_item
    print("Your original item is", business_names[business_names['business_id'] == str(idx)]['name'].values)
    recommends = business_categories_sim.loc[str(idx)].sort_values(ascending = False)[1:].index
    cba1 = []
    for i in range(top_n):
        rec_restaurant = recommends[i]
        cba1.append(business_names[business_names['business_id'] == rec_restaurant]['name'].values[0])
        print("my number ", i+1, " recommendation is ", business_names[business_names['business_id'] == rec_restaurant]['name'].values)
    return cba1

In [16]:
business.name[business.business_id == 'WnT9NIzQgLlILjPT0kEcsQ'].values[0]

'Adelita Taqueria & Restaurant'

In [17]:
# Let's see what restaurants to go to after going to restaurant Adelita Taqueria & Restaurant
recommendations_cba1 = print_recommendations('WnT9NIzQgLlILjPT0kEcsQ', 10)

Your original item is ['Adelita Taqueria & Restaurant']
my number  1  recommendation is  ['Los Taquitos de Puebla ']
my number  2  recommendation is  ['San Miguelito Mexican Cuisine']
my number  3  recommendation is  ['Tamalex Restaurant']
my number  4  recommendation is  ['Chipotle Mexican Grill']
my number  5  recommendation is  ['Mole Poblano Restaurant']
my number  6  recommendation is  ['Fiesta Acapulco']
my number  7  recommendation is  ['Que Chula Es Puebla']
my number  8  recommendation is  ['Kilimandjaro Restaurant']
my number  9  recommendation is  ["Beck's Cajun Cafe"]
my number  10  recommendation is  ['MÃ©xico Lindo']

In [18]:
recommendations_cba1

['Los Taquitos de Puebla ',
 'San Miguelito Mexican Cuisine',
 'Tamalex Restaurant',
 'Chipotle Mexican Grill',
 'Mole Poblano Restaurant',
 'Fiesta Acapulco',
 'Que Chula Es Puebla',
 'Kilimandjaro Restaurant',
 "Beck's Cajun Cafe",
 'MÃ©xico Lindo']

Approach 2

In [19]:
from scipy.sparse import csr_matrix
from pandas.api.types import CategoricalDtype


user_u = list(sorted(review.user_id.unique()))
business_u = list(sorted(review.business_id.unique()))

cat_type_user = CategoricalDtype(categories=user_u, ordered=True)
cat_type_business = CategoricalDtype(categories=business_u, ordered=True)

row = review.user_id.astype(cat_type_user).cat.codes
col = review.business_id.astype(cat_type_business).cat.codes

data = review['stars'].tolist()

sparse_matrix = csr_matrix((data, (row, col)), shape=(len(user_u), len(business_u)))

In [20]:
sparse_matrix

<184805x4372 sparse matrix of type '<class 'numpy.intc'>'
	with 530993 stored elements in Compressed Sparse Row format>

In [21]:
df = pd.DataFrame.sparse.from_spmatrix(sparse_matrix,index=user_u, columns=business_u)

In [22]:
df.head()

,-0TffRSXXIlBYVbb5AwfTg,-1B9pP_CrRBJYPICE5WbRA,-3ArWZfDjfab8qVHf3WVtg,-3m_nXlyvdKAVNNmVirpGQ,-5Rah4ZvWsDu4oilUZxhtw,-63ytt5vkWof-M9NDGTkng,-6MEKOmFu6jckT3pruSxHg,-ATiAtTikuGuqvaW2O6tNA,-AanHawaDlzWHQjrqRRWig,-Bhoyo7LL97tgt9Hze0Saw,...,zuEdIZKAYBDfPjyFg6B34Q,zuKnCtZQKZqnvEaKVnwVVQ,zucC7rHpXPYBu7aEqj0NUw,zujdPV3HT-Y-CKE1GgkMHQ,zvvl3c1FO3O3BZdhusficA,zwTmOj4B_OVPMTMYijQiKg,zwd4dyQ5ovnjVojWfAuhMw,zxRmQ_FWVowh8rlzLCSURQ,zxY4DgtXsVHihSUpsmwamg,zz3E7kmJI2r2JseE6LAnrw
--2tyArRmSoyKx5r-FVG0A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
--2vR0DIsmQ6WfcSzKWigw,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
--4AjktZiHowEIBCMd4CZA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
--4_p6Z3tKadJcr9Non_Vw,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
--6GckBYtTa4hj8pT09oAg,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
# First extract the rating matrix of user id 1
user_rating = df.loc[df.index == '--2tyArRmSoyKx5r-FVG0A',:]

# Fill the missing values with 0
user_rating = user_rating.fillna(0)

In [24]:
# Now let's create the weighted attribute matrix for the movies the user has watched
weighted_attribute = pd.DataFrame(columns = business_categories.columns)
watched = np.where(user_rating.iloc[0,:] != 0)[0] # Which movies did the user rated
restaurant_id = user_rating.columns[watched] # The IDs of the rated movies
for i in range(len(watched)):
    ID = restaurant_id[i]
    scores = np.array(user_rating.iloc[:,watched[i]]) * np.array(business_categories.loc[str(ID),:]) # Calculate the weighted attributes
    scores = pd.DataFrame(scores).T # Convert the result from array to dataframe
    scores.columns = business_categories.columns # Attach column names to the dataframe
    weighted_attribute = weighted_attribute.append(scores)

weighted_attribute.index = restaurant_id # Add the movie indices to the dataframe

In [25]:
weighted_attribute # This is what the weighted attribute looks like

,AcceptsInsurance,Alcohol,Ambience,BYOB,BestNights,BikeParking,BusinessAcceptsBitcoin,BusinessAcceptsCreditCards,BusinessParking,ByAppointmentOnly,...,Seafood Markets,Wraps,Shaved Ice,Cupcakes,Greek,Flowers & Gifts,Home & Garden,French,Candy Stores,Chocolatiers & Shops
IXRSMV7U5D0sYJvArEbm5g,0,3,3,0,3,3,0,3,3,0,...,0,0,0,0,0,0,0,0,0,0
eoN0GAIRV0WmwUm7FmzKgQ,0,4,4,0,4,4,0,4,4,0,...,0,0,0,0,0,0,0,0,0,0

In [26]:
# Next we will create the scaled attribute score
scaled_attribute = np.sum(weighted_attribute, axis = 0)/ np.sum(np.sum(weighted_attribute))

In [27]:
# Now for each unseen movie, calculate the weighted rating 

# Remove watched movies from the movie attribute matrix
restaurant_drop = business_categories.drop(index = map(str, restaurant_id))

# Calculate the weighted rating
weighted_rating = restaurant_drop.mul(scaled_attribute, axis=1)

# And get the overall rating for each movie
new_ratings = np.sum(weighted_rating, axis = 1)

In [28]:
# Sort the new ratings in descending order
nr = new_ratings.sort_values(ascending = False)

# First recommendation
print("Recommendation is ", business_names[business_names['business_id'] == nr.index[0]]['name'].values)

Recommendation is  ['Aki Nom Nom Sushi & Ramen']

In [29]:
ratings = df

In [30]:
def print_recommendations2(uid, top_n):
    """
    inputs: uid <int>: is the id of the user we want to make 
                                 recommendation for
            top_n <int>: number of items we want to recommend for the 
                         original item
    """
    # Extract the user rating
    user_rating = ratings.loc[ratings.index == uid,:]
    user_rating = user_rating.fillna(0)

    # Calculate the weighted attributes
    weighted_attribute = pd.DataFrame(columns = business_categories.columns)
    watched = np.where(user_rating.iloc[0,:] != 0)[0] # Which movies did the user rated
    restaurant_id = user_rating.columns[watched] # The IDs of the rated movies
    for i in range(len(watched)):
        ID = restaurant_id[i]
        scores = np.array(user_rating.iloc[:,watched[i]]) * np.array(business_categories.loc[str(ID),:])
        scores = pd.DataFrame(scores).T
        scores.columns = business_categories.columns
        weighted_attribute = weighted_attribute.append(scores)

    # Obtain new rating
    scaled_attribute = np.sum(weighted_attribute, axis = 0)/ np.sum(np.sum(weighted_attribute))
    restaurant_drop = business_categories.drop(index = map(str, restaurant_id))
    weighted_rating = restaurant_drop.mul(scaled_attribute, axis=1)
    new_ratings = np.sum(weighted_rating, axis = 1)
    nr = new_ratings.sort_values(ascending = False)
    
    # Print the movies the user has watched
    restaurants_visited = []
    for i in range(len(restaurant_id)):
        restaurants_visited.append(business_names[business_names['business_id'] == str(restaurant_id[i])]['name'].values)

    flat_list = [item for sublist in restaurants_visited for item in sublist]
    print('The user has visited these restaurants: \n')
    print('; '.join(flat_list), '\n')
    cba2 = []
    # Recommendations
    for i in range(top_n):
        cba2.append(business_names[business_names['business_id'] == nr.index[i]]['name'].values[0])
        print("Recommendation", i, "is ", business_names[business_names['business_id'] == nr.index[i]]['name'].values)
    return cba2

In [31]:
recommendations_cba2 = print_recommendations2('--2tyArRmSoyKx5r-FVG0A',10)

The user has visited these restaurants:

Finn McCool's Ale House; Yakitori Boy

Recommendation 0 is  ['Aki Nom Nom Sushi & Ramen']
Recommendation 1 is  ['Yamitsuki Ramen']
Recommendation 2 is  ['Alamodak Restaurant and Hookah Lounge']
Recommendation 3 is  ["Jerry's Bar"]
Recommendation 4 is  ["P. J. Clarke's"]
Recommendation 5 is  ["Ruth's Chris Steak House"]
Recommendation 6 is  ['Cleavers']
Recommendation 7 is  ['Hard Rock Cafe']
Recommendation 8 is  ["Moriarty's Restaurant and Irish Pub"]
Recommendation 9 is  ["Chick's Philly"]

In [32]:
recommendations_cba2

['Aki Nom Nom Sushi & Ramen',
 'Yamitsuki Ramen',
 'Alamodak Restaurant and Hookah Lounge',
 "Jerry's Bar",
 "P. J. Clarke's",
 "Ruth's Chris Steak House",
 'Cleavers',
 'Hard Rock Cafe',
 "Moriarty's Restaurant and Irish Pub",
 "Chick's Philly"]

# Recommendation Engine - 2

In [33]:
ratings.fillna(0, inplace = True)

In [34]:
# Matrix Factorization

In [35]:
def matrix_factorization(R, P, Q, K, steps=3, alpha=0.0002, beta=0.02):
    '''
    Inputs:
    R     : The ratings (of dimension M x N)
    P     : an initial matrix of dimension M x K
    Q     : an initial matrix of dimension N x K
    K     : the number of latent features
    steps : the maximum number of steps to perform the optimization
    alpha : the learning rate
    beta  : the regularization parameter

    Outputs:
    the final matrices P and Q
    '''

    for step in range(steps):
        for i in range(R.shape[0]):
            for j in range(R.shape[1]):
                if R[i][j] > 0: # Skipping over missing ratings
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = np.dot(P,Q)
        e = 0
        for i in range(R.shape[0]):
            for j in range(R.shape[1]):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * ( pow(P[i][k],2) + pow(Q[k][j],2) )
        if e < 0.001: # tolerance
            break
    print(e)
    return P, Q

In [36]:
np.random.seed(862)

# Initializations
M = ratings.shape[0] # Number of users
N = ratings.shape[1] # Number of items
K = 3 # Number of latent features

# Initial estimate of P and Q
P = np.random.rand(M,K)
Q = np.random.rand(K,N)
rating_np = np.array(ratings)

In [37]:
P, Q = matrix_factorization(rating_np, P, Q, K)

MemoryError: Unable to allocate 6.02 GiB for an array with shape (184805, 4372) and data type float64

In [ ]:
predicted_rating = np.matmul(P, Q)
predicted_rating = pd.DataFrame(predicted_rating, index = ratings.index, columns = ratings.columns)
predicted_rating.head()

In [ ]:
UID = '--2tyArRmSoyKx5r-FVG0A'

In [ ]:
# Obtain the missing ratings
missing_ratings = predicted_rating.loc[UID][ratings.loc[UID,:]==0]

# Attach it with indices
missing_ratings = pd.Series(missing_ratings, index = ratings.columns[ratings.loc[UID,:] == 0] )

# Sort the ratings
missing_ratings.sort_values(ascending = False, inplace = True)

In [ ]:
 
    
# Recommendations
mat_fact = []
for i in range(10):
    rec_rest_id = missing_ratings.index[i]
    mat_fact.append(business[business['business_id'] == rec_rest_id]['name'].values[0])
    print("my number ", i+1, " recommendation is ", business[business['business_id'] == rec_rest_id]['name'].values[0], 
          ", with a predicted rating of", missing_ratings.iloc[i])

In [ ]:
mat_fact

# SVD

In [ ]:
# Load the libraries
from surprise import Reader
from surprise import Dataset
from surprise.prediction_algorithms.matrix_factorization import SVD

In [ ]:
# Step 1: Set up the reader class
reader = Reader(rating_scale=(1,5))

In [ ]:
# Step 2: Load the dataframe. Use the merged data from above (not the pivoted data)
data = Dataset.load_from_df(review[['user_id', 'business_id', 'stars']], reader)

In [ ]:
# Step 3: Build the train set
svd_data = data.build_full_trainset()

In [ ]:
# Use as many boxes as you need
# Set up the model and fit the model. Note it will take a few minutes to run
svd = SVD(n_factors = 7, lr_all = 0.01, reg_all = 0.1, biased = True,verbose = True, random_state = 862)
svd.fit(svd_data)

In [ ]:
# Use as many boxes as you need
# I will use the predict function (because why not)
# First we need to obtain the ids of the unread books. 
unread_ids = ratings.columns[ratings.loc[UID,:] == 0]

# Now we will loop over the books to extract the predictions
svd_rec = []
for iid in unread_ids:
    svd_rec.append(svd.predict(uid=UID,iid=iid).est)

# Put the result in a pd Series and sort
svd_rec = pd.Series(svd_rec, index = unread_ids).sort_values(ascending=False)

In [ ]:
# Recommendations
svd_pp = []
for i in range(10):
    rec_rest_id = svd_rec.index[i]
    svd_pp.append(business[business['business_id'] == rec_rest_id]['name'].values[0])
    print("my number ", i+1, " recommendation is ", business[business['business_id'] == rec_rest_id]['name'].values[0], 
          ", with a predicted rating of", svd_rec.iloc[i])

In [ ]:
review = review.drop(columns = ['review_id','year'])

In [ ]:
min_rest_ratings = 50
filter_rests = review['business_id'].value_counts() > min_rest_ratings
filter_rests = filter_rests[filter_rests].index.tolist()

min_user_ratings = 50
filter_users = review['user_id'].value_counts() > min_user_ratings
filter_users = filter_users[filter_users].index.tolist()

df_new = review[(review['business_id'].isin(filter_rests)) & (review['user_id'].isin(filter_users))]
print('The original data frame shape:\t{}'.format(review.shape))
print('The new data frame shape:\t{}'.format(df_new.shape))

In [ ]:
reader = Reader(rating_scale=(0, 5))
data = Dataset.load_from_df(df_new[['user_id', 'business_id', 'stars']], reader)

In [ ]:
import pandas as pd
from surprise import Reader
from surprise import Dataset
from surprise.model_selection import cross_validate
from surprise import NormalPredictor
from surprise import KNNBasic
from surprise import KNNWithMeans
from surprise import KNNWithZScore
from surprise import KNNBaseline
from surprise import SVD
from surprise import BaselineOnly
from surprise import SVDpp
from surprise import NMF
from surprise import SlopeOne
from surprise import CoClustering
from surprise.accuracy import rmse
from surprise import accuracy
from surprise.model_selection import train_test_split

In [ ]:

benchmark = []
# Iterate over all algorithms
for algorithm in [SVD(),SVDpp(), SlopeOne(), NMF(), NormalPredictor(), KNNBaseline(), KNNBasic(), KNNWithMeans(), KNNWithZScore(), BaselineOnly(), CoClustering()]:
    # Perform cross validation
    results = cross_validate(algorithm, data, measures=['RMSE'], cv=3, verbose=False)
    
    # Get results & append algorithm name
    tmp = pd.DataFrame.from_dict(results).mean(axis=0)
    tmp = tmp.append(pd.Series([str(algorithm).split(' ')[0].split('.')[-1]], index=['Algorithm']))
    benchmark.append(tmp)
    
pd.DataFrame(benchmark).set_index('Algorithm').sort_values('test_rmse')

In [ ]:
surprise_results = pd.DataFrame(benchmark).set_index('Algorithm').sort_values('test_rmse')

In [ ]:
surprise_results

In [ ]:
#Base Line Only has the best test rmse
print('Using ALS')
bsl_options = {'method': 'als',
               'n_epochs': 5,
               'reg_u': 12,
               'reg_i': 5
               }
algo = BaselineOnly(bsl_options=bsl_options)
cross_validate(algo, data, measures=['RMSE'], cv=3, verbose=False)

In [ ]:
trainset, testset = train_test_split(data, test_size=0.25)
algo = BaselineOnly(bsl_options=bsl_options)
predictions = algo.fit(trainset).test(testset)
accuracy.rmse(predictions)

In [ ]:
trainset = algo.trainset
print(algo.__class__.__name__)

In [ ]:
def get_Iu(uid):
    """ return the number of items rated by given user
    args: 
      uid: the id of the user
    returns: 
      the number of items rated by the user
    """
    try:
        return len(trainset.ur[trainset.to_inner_uid(uid)])
    except ValueError: # user was not part of the trainset
        return 0
    
def get_Ui(iid):
    """ return number of users that have rated given item
    args:
      iid: the raw id of the item
    returns:
      the number of users that have rated the item.
    """
    try: 
        return len(trainset.ir[trainset.to_inner_iid(iid)])
    except ValueError:
        return 0
    
df = pd.DataFrame(predictions, columns=['uid', 'iid', 'rui', 'est', 'details'])
df['Iu'] = df.uid.apply(get_Iu)
df['Ui'] = df.iid.apply(get_Ui)
df['err'] = abs(df.est - df.rui)

In [ ]:
df.head()

In [ ]:
best_predictions = df.sort_values(by='err')[:10]
worst_predictions = df.sort_values(by='err')[-10:]

In [ ]:
best_predictions

In [ ]:
worst_predictions

In [ ]:
df_new.loc[df_new['business_id'] == '3VA5BgRcVd-mAvSFJFFveQ']['stars'].describe()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib notebook

df_new.loc[df_new['business_id'] == '3VA5BgRcVd-mAvSFJFFveQ']['stars'].hist()
plt.xlabel('rating')
plt.ylabel('Number of ratings')
plt.title('Number of ratings restaurant 3VA5BgRcVd-mAvSFJFFveQ has received')
plt.show();